apiVersion: v1
kind: Secret
metadata:
  name: ai-orchestrator-secrets
  namespace: alt-las
type: Opaque
data:
  # Bu değerler base64 ile kodlanmıştır
  # Gerçek ortamda güvenli bir şekilde yönetilmelidir
  # echo -n "your-openai-api-key" | base64
  OPENAI_API_KEY: eW91ci1vcGVuYWktYXBpLWtleQ==
