openapi: 3.0.0
info:
  title: ALT_LAS API Gateway
  description: API Gateway for ALT_LAS project - Platform designed to manage computer systems with artificial intelligence
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.alt-las.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
    
    SegmentationRequest:
      type: object
      required:
        - command
      properties:
        command:
          type: string
          description: Command text
        mode:
          type: string
          enum: [Normal, Dream, Explore, Chaos]
          default: Normal
        persona:
          type: string
          enum: [empathetic_assistant, technical_expert, creative_designer, security_focused, efficiency_optimizer, learning_tutor]
          default: technical_expert
        metadata:
          type: object
          additionalProperties: true
    
    SegmentationResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [success, error, pending]
        altFile:
          type: string
        metadata:
          type: object
          properties:
            timestamp:
              type: string
              format: date-time
            mode:
              type: string
            persona:
              type: string
    
    RunnerRequest:
      type: object
      required:
        - altFile
      properties:
        altFile:
          type: string
        options:
          type: object
          additionalProperties: true
    
    RunnerResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [success, error, pending, running]
        lastFile:
          type: string
        progress:
          type: number
          minimum: 0
          maximum: 100
    
    ArchiveRequest:
      type: object
      required:
        - lastFile
      properties:
        lastFile:
          type: string
        metadata:
          type: object
          additionalProperties: true
    
    ArchiveResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [success, error]
        atlasId:
          type: string
        successRate:
          type: number
          minimum: 0
          maximum: 100

paths:
  /:
    get:
      summary: API Gateway homepage
      description: Used to verify that the API Gateway is running
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
  /health:
    get:
      summary: Health check
      description: Checks the health status of the API Gateway
      responses:
        '200':
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [UP, DOWN]
  
  /api/v1/segmentation:
    post:
      summary: Command segmentation
      description: Splits a command into subtasks and creates an *.alt file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SegmentationRequest'
      responses:
        '200':
          description: Successful segmentation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentationResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization error
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/v1/segmentation/{id}:
    get:
      summary: Segmentation status
      description: Queries the status of a segmentation process
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Segmentation status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentationResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/v1/runner:
    post:
      summary: Subtask execution
      description: Processes the *.alt file and creates an *.last file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunnerRequest'
      responses:
        '200':
          description: Successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization error
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/v1/runner/{id}:
    get:
      summary: Execution status
      description: Queries the status of an execution process
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/v1/archive:
    post:
      summary: Result archiving
      description: Archives the *.last file and saves it to the *.atlas database
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArchiveRequest'
      responses:
        '200':
          description: Successful archiving
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchiveResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authorization error
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/v1/archive/{id}:
    get:
      summary: Query archive record
      description: Queries an archive record
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Archive record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchiveResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

