apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup-manual
  namespace: alt-las
spec:
  template:
    spec:
      containers:
      - name: postgres-backup
        image: postgres:15-alpine
        command:
        - /bin/bash
        - /scripts/backup.sh
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
        - name: scripts-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: postgres-backup-pvc
      - name: scripts-volume
        configMap:
          name: postgres-backup-scripts
          defaultMode: 0755
