apiVersion: v1
kind: Service
metadata:
  name: segmentation-service
  namespace: alt-las
  labels:
    app: segmentation-service
    component: segmentation
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: segmentation-service
