apiVersion: v1
kind: Service
metadata:
  name: runner-service
  namespace: alt-las
  labels:
    app: runner-service
    component: runner
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: runner-service
