version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: alt_las_api_gateway
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_here # Güvenli bir değerle değiştirilmeli
      - REDIS_URL=redis://redis:6379
      - SEGMENTATION_SERVICE_URL=http://segmentation-service:8000
      - RUNNER_SERVICE_URL=http://runner-service:8080
      - ARCHIVE_SERVICE_URL=http://archive-service:9000
      - AI_ORCHESTRATOR_URL=http://ai-orchestrator:8001
    depends_on:
      - redis
      - segmentation-service
      - runner-service
      - archive-service
      - ai-orchestrator
    volumes:
      - ./api-gateway:/app
      - /app/node_modules # node_modules'ın üzerine yazılmasını engellemek için

  segmentation-service:
    build:
      context: ./segmentation-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: alt_las_segmentation_service
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      # - NATS_URL=nats://nats:4222 # Eğer NATS kullanıyorsa
    volumes:
      - ./segmentation-service:/app
    # depends_on:
      # - nats # Eğer NATS kullanıyorsa

  runner-service:
    build:
      context: ./runner-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: alt_las_runner_service
    environment:
      - RUST_LOG=info
      - RUNNER_AI_SERVICE_URL=http://ai-orchestrator:8001
      # - NATS_URL=nats://nats:4222 # Eğer NATS kullanıyorsa
    depends_on:
      - ai-orchestrator
      # - nats # Eğer NATS kullanıyorsa
    volumes:
      - ./runner-service:/usr/src/runner-service

  archive-service:
    build:
      context: ./archive-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: alt_las_archive_service
    environment:
      - DATABASE_URL=postgres://alt_las_user:alt_las_password@postgres_db:5432/alt_las_archive_db?sslmode=disable
      - NATS_URL=nats://nats:4222 # main.go'da NATS bağlantısı var
      - PORT=9000
    depends_on:
      - postgres_db
      - nats
    volumes:
      - ./archive-service:/app

  ai-orchestrator:
    build:
      context: ./ai-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    container_name: alt_las_ai_orchestrator
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8001
      # - OPENAI_API_KEY=your_openai_key_here # Örnek AI modeli için
    volumes:
      - ./ai-orchestrator:/app

  redis:
    image: "redis:7-alpine"
    container_name: alt_las_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres_db:
    image: postgres:14-alpine
    container_name: alt_las_postgres_db
    environment:
      POSTGRES_USER: alt_las_user
      POSTGRES_PASSWORD: alt_las_password # Güvenli bir değerle değiştirilmeli
      POSTGRES_DB: alt_las_archive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.9-alpine
    container_name: alt_las_nats
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port

volumes:
  postgres_data:
  redis_data:

