version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_SOCKET_URL=http://localhost:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - PORT=3000
      - CLIENT_URL=http://localhost:5173
