apiVersion: v1
kind: Namespace
metadata:
  name: alt-las-dev
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: development
    app: alt-las
---
apiVersion: v1
kind: Namespace
metadata:
  name: alt-las-test
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: test
    app: alt-las
---
apiVersion: v1
kind: Namespace
metadata:
  name: alt-las-staging
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: staging
    app: alt-las
---
apiVersion: v1
kind: Namespace
metadata:
  name: alt-las-prod
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: production
    app: alt-las
