apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestrator
  labels:
    app: ai-orchestrator
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-orchestrator
  template:
    metadata:
      labels:
        app: ai-orchestrator
        app.kubernetes.io/component: backend
    spec:
      # Pod level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: ai-orchestrator
        image: your-registry/alt-las-ai-orchestrator:latest
        ports:
        - containerPort: 8000
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "8000"
        # Container level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-data
          mountPath: /tmp
        - name: models-data
          mountPath: /app/models
        - name: cache-data
          mountPath: /app/cache
        - name: logs-data
          mountPath: /app/logs
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: tmp-data
        emptyDir: {}
      - name: models-data
        persistentVolumeClaim:
          claimName: ai-orchestrator-models-pvc
      - name: cache-data
        emptyDir: {}
      - name: logs-data
        emptyDir: {}
