apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: alt-las
  labels:
    app: api-gateway
    tier: frontend
    version: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: frontend
        version: beta
    spec:
      containers:
      - name: api-gateway
        image: frozen68/api-gateway:beta.v12
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: SEGMENTATION_SERVICE_HOST
          value: "segmentation-service"
        - name: SEGMENTATION_SERVICE_PORT
          value: "8000"
        - name: RUNNER_SERVICE_HOST
          value: "runner-service"
        - name: RUNNER_SERVICE_PORT
          value: "8001"
        - name: ARCHIVE_SERVICE_HOST
          value: "archive-service"
        - name: ARCHIVE_SERVICE_PORT
          value: "8002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: jwt-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      restartPolicy: Always
