apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-prod
  namespace: alt-las-prod
type: Opaque
stringData:
  username: altlas
  password: altlas_password_prod
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-staging
  namespace: alt-las-staging
type: Opaque
stringData:
  username: altlas
  password: altlas_password_staging
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-test
  namespace: alt-las-test
type: Opaque
stringData:
  username: altlas
  password: altlas_password_test
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-dev
  namespace: alt-las-dev
type: Opaque
stringData:
  username: altlas
  password: altlas_password_dev
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-prod
  namespace: alt-las-prod
type: Opaque
stringData:
  nats-auth-token: "secure-nats-token-prod"
  prometheus-auth-token: "secure-prometheus-token-prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-staging
  namespace: alt-las-staging
type: Opaque
stringData:
  nats-auth-token: "secure-nats-token-staging"
  prometheus-auth-token: "secure-prometheus-token-staging"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate-prod
  namespace: alt-las-prod
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDETCCAfmgAwIBAgIJALBhQEEuWrWpMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNV
    BAMMFGFsdC1sYXMuZXhhbXBsZS5jb20wHhcNMjUwNDI4MDAwMDAwWhcNMjYwNDI4
    MDAwMDAwWjAfMR0wGwYDVQQDDBRhbHQtbGFzLmV4YW1wbGUuY29tMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxxx5K1jMgwMvH/bBQBUGTm1vQCgvpqv7
    XVkxl5JH+z5Pmux7xKJPsMGEDacSgwH7z0TBtUIY0p8LFGz/Bbh6EQM7tCcPNu6z
    7rzPB9NlS9QrQGTzCbQNjYk6yR+VWG1CS0K5xZ8JSO+QQ1YgGwOBZlbY9TBLiXrP
    EXAMPLE_CERTIFICATE_DATA_PROD
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHHHkrWMyDAy8f
    9sFAFQZObW9AKC+mq/tdWTGXkkf7Pk+a7HvEok+wwYQNpxKDAfvPRMG1QhjSnwsU
    bP8FuHoRAzu0Jw827rPuvM8H02VL1CtAZPMJtA2NiTrJH5VYbUJLQrnFnwlI75BD
    EXAMPLE_PRIVATE_KEY_DATA_PROD
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-orchestrator-secrets-prod
  namespace: alt-las-prod
type: Opaque
stringData:
  model-api-key: "ai-model-api-key-prod"
  cache-encryption-key: "cache-encryption-key-prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: runner-service-secrets-prod
  namespace: alt-las-prod
type: Opaque
stringData:
  execution-token: "secure-execution-token-prod"
  storage-access-key: "storage-access-key-prod"
