apiVersion: batch/v1
kind: Job
metadata:
  name: acceptance-tests
  namespace: alt-las
  labels:
    app: acceptance-tests
    component: testing
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: acceptance-tests
        component: testing
    spec:
      restartPolicy: Never
      containers:
      - name: acceptance-tests
        image: alt-las/acceptance-tests:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway:3000"
        - name: SEGMENTATION_SERVICE_URL
          value: "http://segmentation-service:8000"
        - name: RUNNER_SERVICE_URL
          value: "http://runner-service:8080"
        - name: ARCHIVE_SERVICE_URL
          value: "http://archive-service:9000"
        - name: AI_ORCHESTRATOR_URL
          value: "http://ai-orchestrator:8001"
        - name: TEST_TIMEOUT
          value: "300"
        - name: LOG_LEVEL
          value: "info"
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting Acceptance Tests..."
          
          # Wait for all services to be ready
          echo "Waiting for API Gateway..."
          until curl -s http://api-gateway:3000/health | grep -q "ok"; do
            sleep 5
          done
          
          echo "All services are ready. Running acceptance tests..."
          
          # Run acceptance tests
          cd /app
          npm run test:acceptance
          
          # Check test results
          if [ $? -eq 0 ]; then
            echo "Acceptance tests passed!"
            exit 0
          else
            echo "Acceptance tests failed!"
            exit 1
          fi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: test-results
          mountPath: /app/test-results
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: test-results
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
