apiVersion: v1
kind: Service
metadata:
  name: ai-orchestrator
  namespace: alt-las
  labels:
    app: ai-orchestrator
    component: ai
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ai-orchestrator
