apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-config
  namespace: alt-las
data:
  canary-deployment-strategy.yaml: |
    # Canary Dağıtım Stratejisi
    
    ## Aşama 1: İlk Dağıtım (%10)
    - name: initial-deployment
      trafficPercentage: 10
      duration: 1h
      metrics:
        - name: error-rate
          threshold: 1%
        - name: latency-p95
          threshold: 500ms
    
    ## Aşama 2: Genişletilmiş Dağıtım (%30)
    - name: expanded-deployment
      trafficPercentage: 30
      duration: 2h
      metrics:
        - name: error-rate
          threshold: 1%
        - name: latency-p95
          threshold: 500ms
    
    ## Aşama 3: Yarı Dağıtım (%50)
    - name: half-deployment
      trafficPercentage: 50
      duration: 4h
      metrics:
        - name: error-rate
          threshold: 1%
        - name: latency-p95
          threshold: 500ms
    
    ## Aşama 4: Tam Dağıtım (%100)
    - name: full-deployment
      trafficPercentage: 100
      metrics:
        - name: error-rate
          threshold: 1%
        - name: latency-p95
          threshold: 500ms
  
  canary-rollback-strategy.yaml: |
    # Canary Geri Alma Stratejisi
    
    ## Otomatik Geri Alma Koşulları
    - name: error-rate
      threshold: 2%
      duration: 5m
      action: rollback
    
    - name: latency-p95
      threshold: 1000ms
      duration: 5m
      action: rollback
    
    - name: cpu-usage
      threshold: 90%
      duration: 5m
      action: rollback
    
    - name: memory-usage
      threshold: 90%
      duration: 5m
      action: rollback
    
    ## Geri Alma Prosedürü
    rollbackProcedure:
      - step: pause-deployment
        description: "Yeni sürüm dağıtımını durdur"
      
      - step: redirect-traffic
        description: "Tüm trafiği eski sürüme yönlendir"
      
      - step: scale-down-new-version
        description: "Yeni sürüm pod'larını sıfıra indir"
      
      - step: notify
        description: "Geri alma durumunu bildir"
  
  canary-metrics.yaml: |
    # Canary Dağıtım Metrikleri
    
    ## Temel Metrikler
    - name: error-rate
      description: "HTTP 5xx hata oranı"
      query: 'sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))'
      threshold: 1%
    
    - name: latency-p95
      description: "HTTP isteklerinin %95 yüzdelik dilim gecikme süresi"
      query: 'histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))'
      threshold: 500ms
    
    - name: success-rate
      description: "HTTP 2xx başarı oranı"
      query: 'sum(rate(http_requests_total{status=~"2.."}[5m])) / sum(rate(http_requests_total[5m]))'
      threshold: 99%
    
    ## Kaynak Kullanım Metrikleri
    - name: cpu-usage
      description: "CPU kullanımı"
      query: 'sum(rate(container_cpu_usage_seconds_total{container_name!="POD"}[5m])) by (pod)'
      threshold: 80%
    
    - name: memory-usage
      description: "Bellek kullanımı"
      query: 'sum(container_memory_usage_bytes{container_name!="POD"}) by (pod) / sum(container_spec_memory_limit_bytes{container_name!="POD"}) by (pod)'
      threshold: 80%
    
    ## İş Metrikleri
    - name: processed-documents
      description: "İşlenen belge sayısı"
      query: 'sum(rate(documents_processed_total[5m]))'
      threshold: 10
    
    - name: processing-time
      description: "Belge işleme süresi"
      query: 'histogram_quantile(0.95, sum(rate(document_processing_duration_seconds_bucket[5m])) by (le))'
      threshold: 2s
