apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-service-v2
  namespace: alt-las
  labels:
    app: segmentation-service
    component: segmentation
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segmentation-service
      version: v2
  template:
    metadata:
      labels:
        app: segmentation-service
        component: segmentation
        version: v2
    spec:
      serviceAccountName: segmentation-service
      containers:
      - name: segmentation-service
        image: alt-las/segmentation-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "altlas_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: AI_ORCHESTRATOR_URL
          value: "http://ai-orchestrator:8001"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      volumes:
      - name: config-volume
        configMap:
          name: segmentation-service-config
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: segmentation-service
  namespace: alt-las
spec:
  hosts:
  - segmentation-service
  http:
  - route:
    - destination:
        host: segmentation-service
        subset: v1
      weight: 90
    - destination:
        host: segmentation-service
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: segmentation-service
  namespace: alt-las
spec:
  host: segmentation-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
