apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-manager
  namespace: alt-las
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-manager-role
  namespace: alt-las
rules:
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-manager-binding
  namespace: alt-las
subjects:
- kind: ServiceAccount
  name: backup-manager
  namespace: alt-las
roleRef:
  kind: Role
  name: backup-manager-role
  apiGroup: rbac.authorization.k8s.io
