apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-orchestrator-config
  namespace: atlas-production
data:
  ENVIRONMENT: "production"
  PORT: "8001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "atlas_user"
  DB_USER: "atlas_user"
  DB_PASSWORD: "atlas_password"
  SEGMENTATION_SERVICE_URL: "http://segmentation-service:8000"
  LOG_LEVEL: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestrator
  namespace: atlas-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-orchestrator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-orchestrator
    spec:
      containers:
      - name: ai-orchestrator
        image: frozen68/ai-orchestrator:production
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: ai-orchestrator-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ai-orchestrator
  namespace: atlas-production
spec:
  selector:
    app: ai-orchestrator
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
