apiVersion: v1
kind: Secret
metadata:
  name: alt-las-secrets
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret"
  REDIS_PASSWORD: "your-redis-password"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "altlas"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-db:5432/altlas"
  OPENAI_API_KEY: "your-openai-api-key"
