apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: alt-las
  labels:
    app: api-gateway
    component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
        version: v1
    spec:
      serviceAccountName: api-gateway
      containers:
      - name: api-gateway
        image: alt-las/api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: JWT_SECRET
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: REDIS_URL
        - name: SEGMENTATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: SEGMENTATION_SERVICE_URL
        - name: RUNNER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: RUNNER_SERVICE_URL
        - name: ARCHIVE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: ARCHIVE_SERVICE_URL
        - name: AI_ORCHESTRATOR_URL
          valueFrom:
            configMapKeyRef:
              name: api-gateway-config
              key: AI_ORCHESTRATOR_URL
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
