version: '3'

services:
  ai-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - MODEL_DIR=/app/models
      - CACHE_DIR=/app/cache
      - LOG_LEVEL=INFO
      - USE_GPU=true
    restart: unless-stopped
