apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: alt-las
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: segmentation-service
  namespace: alt-las
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-service
  namespace: alt-las
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: archive-service
  namespace: alt-las
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-orchestrator
  namespace: alt-las
