global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanager:9093

# Rule files
rule_files:
  # - "/etc/prometheus/rules/gpu_rules.yml"
  # - "/etc/prometheus/rules/api_sla_rules.yml"

# Scrape configurations
scrape_configs:
  # NVIDIA DCGM Exporter
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
        labels:
          instance: 'gpu-node'

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'gpu-node'

  # AI Orchestrator Service
  - job_name: 'ai-orchestrator'
    static_configs:
      - targets: ['ai-orchestrator:8000']
        labels:
          service: 'ai-orchestrator'
          instance: 'gpu-node'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          instance: 'grafana'
