apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-secrets-reader
  namespace: alt-las-prod
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["api-keys-prod", "tls-certificate-prod"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-orchestrator-secrets-reader
  namespace: alt-las-prod
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ai-orchestrator-secrets-prod", "db-credentials-prod"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-service-secrets-reader
  namespace: alt-las-prod
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["runner-service-secrets-prod"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-secrets-binding
  namespace: alt-las-prod
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: alt-las-prod
roleRef:
  kind: Role
  name: api-gateway-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-orchestrator-secrets-binding
  namespace: alt-las-prod
subjects:
- kind: ServiceAccount
  name: ai-orchestrator-sa
  namespace: alt-las-prod
roleRef:
  kind: Role
  name: ai-orchestrator-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-service-secrets-binding
  namespace: alt-las-prod
subjects:
- kind: ServiceAccount
  name: runner-service-sa
  namespace: alt-las-prod
roleRef:
  kind: Role
  name: runner-service-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: alt-las-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-orchestrator-sa
  namespace: alt-las-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-service-sa
  namespace: alt-las-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: segmentation-service-sa
  namespace: alt-las-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: archive-service-sa
  namespace: alt-las-prod
