apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-service
  namespace: alt-las
  labels:
    app: segmentation-service
    tier: backend
    version: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: segmentation-service
  template:
    metadata:
      labels:
        app: segmentation-service
        tier: backend
        version: beta
    spec:
      containers:
      - name: segmentation-service
        image: frozen68/segmentation-service:beta.v5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "8000"
        - name: MEMORY_THRESHOLD_MB
          value: "500"
        - name: HIGH_MEMORY_THRESHOLD_MB
          value: "1000"
        - name: GC_INTERVAL
          value: "60"
        - name: MAX_CACHE_SIZE
          value: "100"
        - name: DISABLE_SPACY
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: logs-volume
        emptyDir: {}
      restartPolicy: Always
