apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v2
  namespace: alt-las
  labels:
    app: api-gateway
    component: gateway
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: v2
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
        version: v2
    spec:
      serviceAccountName: api-gateway
      containers:
      - name: api-gateway
        image: alt-las/api-gateway:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_PASSWORD
        - name: SEGMENTATION_SERVICE_URL
          value: "http://segmentation-service:8000"
        - name: RUNNER_SERVICE_URL
          value: "http://runner-service:8080"
        - name: ARCHIVE_SERVICE_URL
          value: "http://archive-service:9000"
        - name: AI_ORCHESTRATOR_URL
          value: "http://ai-orchestrator:8001"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      volumes:
      - name: config-volume
        configMap:
          name: api-gateway-config
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway
  namespace: alt-las
spec:
  hosts:
  - api-gateway
  http:
  - route:
    - destination:
        host: api-gateway
        subset: v1
      weight: 90
    - destination:
        host: api-gateway
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-gateway
  namespace: alt-las
spec:
  host: api-gateway
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
