apiVersion: v1
kind: Service
metadata:
  name: archive-service
  namespace: alt-las
  labels:
    app: archive-service
    component: archive
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: archive-service
