apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: alt-las
type: Opaque
data:
  # Bu değerler base64 ile kodlanmıştır
  # Gerçek ortamda güvenli bir şekilde yönetilmelidir
  # echo -n "your-jwt-secret-key-here" | base64
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  REDIS_PASSWORD: eW91ci1yZWRpcy1wYXNzd29yZA==
