name: Node.js CI for API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api_gateway_ci.yml' # Trigger on workflow changes too
  pull_request:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api_gateway_ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./api-gateway

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: api-gateway/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linters
      run: npm run lint
      
    - name: Run build process
      run: npm run build --if-present
      
    - name: Run tests
      run: npm run test

  build-and-push-docker-image:
    needs: build-and-test # Depends on the build and test job
    runs-on: ubuntu-latest
    # Only run on push to main branch, not on pull requests or other branches
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        file: ./api-gateway/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/alt_las_api_gateway:latest

