apiVersion: v1
kind: ConfigMap
metadata:
  name: alt-las-config
data:
  NODE_ENV: "development"
  SEGMENTATION_SERVICE_URL: "http://segmentation-service:8000"
  RUNNER_SERVICE_URL: "http://runner-service:8080"
  ARCHIVE_SERVICE_URL: "http://archive-service:9000"
  AI_ORCHESTRATOR_URL: "http://ai-orchestrator:8001"
  REDIS_URL: "redis://redis:6379"
  PYTHONUNBUFFERED: "1"
  SEGMENTATION_PORT: "8000"
  ARCHIVE_PORT: "9000"
  AI_PORT: "8001"
  RUST_LOG: "info"
  RUNNER_AI_SERVICE_URL: "http://ai-orchestrator:8001"
  NATS_URL: "nats://nats:4222"
