apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestrator
  namespace: atlas-beta
  labels:
    app: ai-orchestrator
    environment: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-orchestrator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-orchestrator
        environment: beta
    spec:
      containers:
      - name: ai-orchestrator
        image: frozen68/ai-orchestrator:beta
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: PORT
          value: "8001"
        - name: MODEL_CACHE_DIR
          value: "/app/cache"
        - name: LOG_LEVEL
          value: "INFO"
        - name: AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: atlas-secrets
              key: ai_api_key
        volumeMounts:
        - name: model-cache
          mountPath: /app/cache
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: model-cache
        emptyDir: {}
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-orchestrator
  namespace: atlas-beta
  labels:
    app: ai-orchestrator
    environment: beta
spec:
  selector:
    app: ai-orchestrator
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
