name: ALT_LAS CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/api-gateway
            ghcr.io/${{ github.repository }}/segmentation-service
            ghcr.io/${{ github.repository }}/runner-service
            ghcr.io/${{ github.repository }}/archive-service
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
      
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ghcr.io/${{ github.repository }}/api-gateway:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Segmentation Service
        uses: docker/build-push-action@v4
        with:
          context: ./segmentation-service
          push: true
          tags: ghcr.io/${{ github.repository }}/segmentation-service:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Runner Service
        uses: docker/build-push-action@v4
        with:
          context: ./runner-service
          push: true
          tags: ghcr.io/${{ github.repository }}/runner-service:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Archive Service
        uses: docker/build-push-action@v4
        with:
          context: ./archive-service
          push: true
          tags: ghcr.io/${{ github.repository }}/archive-service:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
