name: Docker Security Scan
'on':
  push:
    branches:
    - main
    - master
    paths:
    - '**/Dockerfile*'
    - docker-compose*.yml
    - '**/docker/**'
  pull_request:
    branches:
    - main
    - master
    paths:
    - '**/Dockerfile*'
    - docker-compose*.yml
    - '**/docker/**'
  workflow_dispatch: {}
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: altlas/security-scan:${{ github.sha }}
    - name: Install security scanning tools
      run: sudo apt-get update && sudo apt-get install -y curl git
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: altlas/security-scan:${{ github.sha }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL,HIGH
    - name: Run Hadolint Dockerfile linter
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Run Dockle container linter
      run: "\n                        curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/latest/download/dockle_Linux-64bit.deb\n\
        \                        sudo dpkg -i dockle.deb\n                       \
        \ dockle --exit-code 1 --exit-level fatal altlas/security-scan:${{ github.sha\
        \ }}\n                        "
    - name: Run Docker Bench Security
      run: "\n                        git clone https://github.com/docker/docker-bench-security.git\n\
        \                        cd docker-bench-security\n                      \
        \  sudo sh docker-bench-security.sh -c container_images\n                \
        \        "
    - name: Generate security report
      if: always()
      run: "\n                        mkdir -p security-reports\n                \
        \        echo \"# Docker Security Scan Report\" > security-reports/report.md\n\
        \                        echo \"Date: $(date)\" >> security-reports/report.md\n\
        \                        echo \"Commit: ${{ github.sha }}\" >> security-reports/report.md\n\
        \                        echo \"\" >> security-reports/report.md\n       \
        \                 echo \"## Scan Results\" >> security-reports/report.md\n\
        \                        echo \"\" >> security-reports/report.md\n       \
        \                 echo \"See job logs for detailed results.\" >> security-reports/report.md\n\
        \                        "
    - name: Upload security report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: security-reports/
