name: Enhanced CI/CD Security Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly scan on Mondays at 2 AM

jobs:
  secrets-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.63.2
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      
      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      
      # Added Detect-Secrets for additional coverage
      - name: Detect-Secrets
        run: |
          pip install detect-secrets
          detect-secrets scan --baseline .secrets.baseline
          detect-secrets audit .secrets.baseline

  code-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Added SonarQube scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      # Added SAST with Semgrep
      - name: Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          output: semgrep-results.sarif
      
      # Added dependency scanning
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'ALT_LAS'
          path: '.'
          format: 'HTML'
          out: 'dependency-check-report'
          args: >
            --enableExperimental
            --suppression suppress.xml
      
      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

  sbom-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
      
      # Added CycloneDX SBOM format
      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          path: .
          output: cyclonedx-sbom.json
      
      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sbom-reports
          path: |
            sbom.spdx.json
            cyclonedx-sbom.json

  supply-chain-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: SLSA Provenance Generator
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
        with:
          base-image: ubuntu:latest
          private-repository: false
      
      - name: Verify Dependencies with Sigstore
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/download/v2.2.0/cosign-linux-amd64 -o cosign
          chmod +x cosign
          ./cosign verify-blob --key cosign.pub sbom.spdx.json
      
      # Added in-toto attestation
      - name: Generate in-toto attestation
        run: |
          pip install in-toto
          in-toto-record start -n build -k key.pem
          # Build commands would go here
          in-toto-record stop -n build -k key.pem
          in-toto-verify -l layout.json -k layout-key.pem

  container-security:
    runs-on: ubuntu-latest
    needs: [secrets-scanning, sbom-generation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: altlas/security-scan:${{ github.sha }}
      
      # Enhanced Trivy scan with more options
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: altlas/security-scan:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      
      - name: Run Grype vulnerability scanner
        uses: anchore/scan-action@v3
        with:
          image: altlas/security-scan:${{ github.sha }}
          fail-build: true
          severity-cutoff: high
      
      # Added Clair scanner
      - name: Run Clair scanner
        run: |
          docker run -d --name db arminc/clair-db:latest
          docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:latest
          wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
          chmod +x clair-scanner_linux_amd64
          ./clair-scanner_linux_amd64 --ip $(hostname -i) altlas/security-scan:${{ github.sha }}
      
      - name: Run Falco runtime security
        run: |
          curl -s https://falco.org/repo/falcosecurity-packages.asc | sudo apt-key add -
          echo "deb https://download.falco.org/packages/deb stable main" | sudo tee -a /etc/apt/sources.list.d/falcosecurity.list
          sudo apt-get update -y
          sudo apt-get install -y falco
          sudo falco -c falco.yaml -r falco_rules.yaml -M 60
      
      # Added Docker Scout
      - name: Run Docker Scout
        run: |
          docker scout cves altlas/security-scan:${{ github.sha }}
          docker scout recommendations altlas/security-scan:${{ github.sha }}

  secure-deployment:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
    needs: [container-security, supply-chain-security, code-security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/api-gateway
            ghcr.io/${{ github.repository }}/segmentation-service
            ghcr.io/${{ github.repository }}/runner-service
            ghcr.io/${{ github.repository }}/archive-service
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
      
      # Enhanced signing with Cosign and SBOM attachment
      - name: Sign and push images with Cosign
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/download/v2.2.0/cosign-linux-amd64 -o cosign
          chmod +x cosign
          
          # Build, sign and push each image with SBOM attachment
          for service in api-gateway segmentation-service runner-service archive-service; do
            docker build -t ghcr.io/${{ github.repository }}/$service:${{ steps.meta.outputs.version }} ./$service
            docker push ghcr.io/${{ github.repository }}/$service:${{ steps.meta.outputs.version }}
            ./cosign sign --key cosign.key ghcr.io/${{ github.repository }}/$service:${{ steps.meta.outputs.version }}
            ./cosign attach sbom --sbom sbom.spdx.json ghcr.io/${{ github.repository }}/$service:${{ steps.meta.outputs.version }}
          done
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      
      # Enhanced Kubernetes validation
      - name: Verify deployment with Kubernetes validations
        run: |
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          
          # Validate Kubernetes manifests
          ./kubectl apply --dry-run=client -f kubernetes/ --validate=true
          
          # Run kubeval for additional validation
          curl -L https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar xz
          ./kubeval --strict kubernetes/*.yaml
          
          # Run Conftest for policy validation
          curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz
          tar xzf conftest_0.42.1_Linux_x86_64.tar.gz
          ./conftest test kubernetes/*.yaml -p kubernetes-policies/
      
      # Added security scanning for Kubernetes manifests
      - name: Run Kubesec
        run: |
          curl -LO https://github.com/controlplaneio/kubesec/releases/download/v2.13.0/kubesec_linux_amd64
          chmod +x kubesec_linux_amd64
          for file in kubernetes/*.yaml; do
            ./kubesec_linux_amd64 scan $file >> kubesec-results.txt
          done
      
      - name: Upload security results
        uses: actions/upload-artifact@v4
        with:
          name: security-results
          path: |
            trivy-results.sarif
            kubesec-results.txt
            semgrep-results.sarif
